### ISSUE TITLE
Configuring Different Toolchains for REE and TEE Code in SecApi

### ISSUE THREAD

**Issue by Hanlin928** [rdkcentral/tasecureapi#114]
Hello,

As I understand it, the SecApi codebase is divided into parts that run in the REE (Rich Execution Environment) world and the TEE (Trusted Execution Environment) world. In our environment, the code for REE and TEE is compiled using different toolchains.

I would like to inquire about the existing cmake scripts: Is there a way to separately set different toolchains for the REE and TEE code within the current build system?

Or is it necessary for us to modify the cmake scripts to achieve this? If modifications are required, are there any plans to support such configurations in the future?

Any advice or guidance on how to handle different toolchains for REE and TEE within the cmake setup would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Hanlin.Wang

**Comment by riwoh** [comment]
Hi Hanlin, 

I believe you will need to modify your own CMakeFiles to support whatever build methods you prefer.  Because this is an open source and platform independent implementation, there are no plans to submit any build configurations for any specific platform types.  

For RDK specific implementations, I can guide you in that many other SOC vendors who have implemented this also use 2 different toolchains to build the REE and TEE applications.   Typically the REE side is built along with the rest of the RDK-V project, and the TEE side is built and signed separately, and delivered as a binary.

Richard Woh

**Comment by Hanlin928** [comment]
Thanks for your guidance and suggestions. 
Let me close this issue.
